In [33]:
import pandas as pd

# Read the CSV and Perform Basic Data Cleaning

In [34]:
df = pd.read_csv("features_df.csv")

df = df.dropna(axis='columns', how='all')

df = df.dropna()
df.head()

,actual,estimate,period,symbol,year,quarter,beat,f1_pup,f2_vup,f3_bothup,f4_average_price
0,1.00,1.1300,2019-12-31,YUM,2019,4,0,0.390625,0.437500,0.187500,103.581563
1,0.80,0.9400,2019-09-30,YUM,2019,3,0,0.468750,0.468750,0.171875,114.279531
2,0.93,0.8700,2019-06-30,YUM,2019,2,1,0.619048,0.460317,0.253968,103.853810
3,0.82,0.8100,2019-03-31,YUM,2019,1,1,0.573770,0.557377,0.327869,94.701148
4,0.40,0.9485,2018-12-31,YUM,2018,4,0,0.523810,0.444444,0.285714,89.395556

In [4]:
len(df)

3600

In [5]:
df1 = df.loc[df["beat"] == 0]
len(df1)

677

In [6]:
newdf = df[["symbol", "year", "quarter", "f1_pup", "f2_vup", "f3_bothup", "f4_average_price", "beat", 'estimate']]

In [7]:
df_train = newdf.loc[df["year"] <= 2016]
df_train.head()

,symbol,year,quarter,f1_pup,f2_vup,f3_bothup,f4_average_price,beat,estimate
12,YUM,2016,4,0.507937,0.396825,0.190476,71.011429,1,0.74048
13,YUM,2016,3,0.625000,0.453125,0.265625,88.782500,0,1.10005
14,YUM,2016,2,0.593750,0.500000,0.328125,81.975000,1,0.74036
15,YUM,2016,1,0.524590,0.459016,0.229508,72.983607,1,0.83010
16,YUM,2015,4,0.515625,0.406250,0.187500,72.661250,1,0.66242

In [8]:
df_test = newdf.loc[df["year"] >= 2017]

In [9]:
df_test.head()

,symbol,year,quarter,f1_pup,f2_vup,f3_bothup,f4_average_price,beat,estimate
0,YUM,2019,4,0.390625,0.437500,0.187500,103.581563,0,1.1300
1,YUM,2019,3,0.468750,0.468750,0.171875,114.279531,0,0.9400
2,YUM,2019,2,0.619048,0.460317,0.253968,103.853810,1,0.8700
3,YUM,2019,1,0.573770,0.557377,0.327869,94.701148,1,0.8100
4,YUM,2018,4,0.523810,0.444444,0.285714,89.395556,0,0.9485

# Features

In [11]:
# Set features. This will also be used as your x values.
X_train = df_train[['f1_pup', 'f2_vup', 'f3_bothup', 'f4_average_price', 'estimate']]
X_test = df_test[['f1_pup', 'f2_vup', 'f3_bothup', 'f4_average_price', 'estimate']]
y_train = df_train['beat']
y_test = df_test['beat']
X_test

        f1_pup    f2_vup  f3_bothup  f4_average_price  estimate
0     0.390625  0.437500   0.187500        103.581563   1.13000
1     0.468750  0.468750   0.171875        114.279531   0.94000
2     0.619048  0.460317   0.253968        103.853810   0.87000
3     0.573770  0.557377   0.327869         94.701148   0.81000
4     0.523810  0.444444   0.285714         89.395556   0.94850
5     0.666667  0.444444   0.333333         83.443810   0.82886
6     0.453125  0.562500   0.250000         83.431875   0.74367
7     0.573770  0.475410   0.295082         81.973115   0.68395
8     0.476190  0.349206   0.206349         79.106349   0.79548
9     0.539683  0.523810   0.285714         75.236190   0.66757
10    0.523810  0.428571   0.238095         69.581111   0.61100
11    0.500000  0.500000   0.241935         65.118065   0.59771
72    0.453125  0.437500   0.125000         69.150313   0.43000
73    0.406250  0.468750   0.156250         72.308281   0.67000
74    0.444444  0.507937   0.238095         77.411270   0.66000
75    0.557377  0.442623   0.262295         76.243770   0.70000
76    0.492063  0.476190   0.206349         78.456984   1.07717
77    0.428571  0.428571   0.190476         81.759524   1.23361
78    0.593750  0.484375   0.250000         79.674531   1.26981
79    0.442623  0.508197   0.196721         79.935574   1.12194
80    0.539683  0.555556   0.317460         82.707381   1.03662
81    0.507937  0.539683   0.253968         79.404444   0.86059
82    0.444444  0.507937   0.190476         81.818571   0.83629
83    0.403226  0.500000   0.193548         83.543065   0.84900
144   0.484375  0.468750   0.203125        119.133906   1.09000
145   0.453125  0.453125   0.203125        113.228594   1.22000
146   0.619048  0.412698   0.238095        103.388730   1.02000
147   0.524590  0.409836   0.245902         97.270656   1.33000
148   0.555556  0.444444   0.238095         96.181905   1.01226
149   0.444444  0.412698   0.238095         91.760159   1.21742
...        ...       ...        ...               ...       ...
3390  0.578125  0.531250   0.281250         60.625156   0.70972
3391  0.524590  0.508197   0.229508         60.254426   0.58011
3392  0.571429  0.460317   0.269841         55.418254   0.73217
3393  0.539683  0.523810   0.222222         50.175397   0.65256
3394  0.523810  0.428571   0.238095         45.265556   0.60500
3395  0.596774  0.419355   0.290323         43.232903   0.43000
3456  0.656250  0.468750   0.296875        257.328750   4.55000
3457  0.500000  0.437500   0.218750        209.120703   2.84000
3458  0.539683  0.555556   0.206349        194.892698   2.10000
3459  0.540984  0.508197   0.278689        169.663770   2.36000
3460  0.460317  0.523810   0.222222        193.912063   4.16694
3461  0.571429  0.507937   0.269841        208.300000   2.78306
3462  0.546875  0.484375   0.203125        181.396562   2.18136
3463  0.442623  0.491803   0.213115        172.191311   2.67285
3464  0.523810  0.396825   0.206349        167.148254   3.85700
3465  0.523810  0.460317   0.253968        155.169048   1.86736
3466  0.412698  0.428571   0.174603        147.875397   1.57153
3467  0.645161  0.500000   0.370968        131.712500   2.01987
3528  0.484375  0.468750   0.250000         78.725156   0.85000
3529  0.453125  0.453125   0.156250         72.140000   0.72000
3530  0.555556  0.507937   0.253968         74.087143   0.71000
3531  0.639344  0.491803   0.278689         75.910164   0.73000
3532  0.476190  0.507937   0.253968         67.278889   0.73592
3533  0.587302  0.444444   0.269841         66.176349   0.62731
3534  0.578125  0.437500   0.265625         65.249531   0.64239
3535  0.442623  0.475410   0.180328         70.096066   0.58000
3536  0.555556  0.476190   0.285714         67.493016   0.62433
3537  0.492063  0.476190   0.158730         62.290476   0.52167
3538  0.476190  0.428571   0.190476         56.958730   0.48357
3539  0.580645  0.467742   0.290323         50.475645   0.49000

[600 rows x 5 columns]

# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [12]:
# Scale your data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the Model

In [13]:
from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
classifier.fit(X_train_scaled, y_train)

C:\Users\ashka\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
print(f"Training Data Score: {classifier.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test_scaled, y_test)}")

Training Data Score: 0.8003333333333333
Testing Data Score: 0.87

In [19]:
predictions = classifier.predict(X_test_scaled)

In [20]:
dd = pd.DataFrame({"Prediction": predictions, "Actual":y_test})
dd

      Prediction  Actual
0              1       0
1              1       0
2              1       1
3              1       1
4              1       0
5              1       1
6              1       1
7              1       1
8              1       1
9              1       1
10             1       1
11             1       1
72             1       0
73             1       1
74             1       0
75             1       0
76             1       1
77             1       1
78             1       0
79             1       0
80             1       0
81             1       1
82             1       0
83             1       1
144            1       1
145            1       1
146            1       1
147            1       1
148            1       1
149            1       1
...          ...     ...
3390           1       1
3391           1       1
3392           1       1
3393           1       1
3394           1       1
3395           1       1
3456           1       1
3457           1       1
3458           1       1
3459           1       1
3460           1       1
3461           1       1
3462           1       1
3463           1       1
3464           1       1
3465           1       1
3466           1       1
3467           1       1
3528           1       1
3529           1       1
3530           1       1
3531           1       1
3532           1       1
3533           1       1
3534           1       1
3535           1       1
3536           1       1
3537           1       1
3538           1       1
3539           1       1

[600 rows x 2 columns]

In [21]:
# To Confirm the accuracy of testing data
s = dd["Prediction"].count()
wrong = 0
for i in range(0,s):
    a=dd["Prediction"].iloc[i]
    b=dd["Actual"].iloc[i]
    if a != b:
        wrong = wrong + 1
        
(s - wrong) / s

0.87

In [22]:
df_test['Prediction'] = dd['Prediction']
df_test

C:\Users\ashka\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,symbol,year,quarter,f1_pup,f2_vup,f3_bothup,f4_average_price,beat,estimate,Prediction
0,YUM,2019,4,0.390625,0.437500,0.187500,103.581563,0,1.13000,1
1,YUM,2019,3,0.468750,0.468750,0.171875,114.279531,0,0.94000,1
2,YUM,2019,2,0.619048,0.460317,0.253968,103.853810,1,0.87000,1
3,YUM,2019,1,0.573770,0.557377,0.327869,94.701148,1,0.81000,1
4,YUM,2018,4,0.523810,0.444444,0.285714,89.395556,0,0.94850,1
5,YUM,2018,3,0.666667,0.444444,0.333333,83.443810,1,0.82886,1
6,YUM,2018,2,0.453125,0.562500,0.250000,83.431875,1,0.74367,1
7,YUM,2018,1,0.573770,0.475410,0.295082,81.973115,1,0.68395,1
8,YUM,2017,4,0.476190,0.349206,0.206349,79.106349,1,0.79548,1
9,YUM,2017,3,0.539683,0.523810,0.285714,75.236190,1,0.66757,1
10,YUM,2017,2,0.523810,0.428571,0.238095,69.581111,1,0.61100,1
11,YUM,2017,1,0.500000,0.500000,0.241935,65.118065,1,0.59771,1
72,XOM,2019,4,0.453125,0.437500,0.125000,69.150313,0,0.43000,1
73,XOM,2019,3,0.406250,0.468750,0.156250,72.308281,1,0.67000,1
74,XOM,2019,2,0.444444,0.507937,0.238095,77.411270,0,0.66000,1
75,XOM,2019,1,0.557377,0.442623,0.262295,76.243770,0,0.70000,1
76,XOM,2018,4,0.492063,0.476190,0.206349,78.456984,1,1.07717,1
77,XOM,2018,3,0.428571,0.428571,0.190476,81.759524,1,1.23361,1
78,XOM,2018,2,0.593750,0.484375,0.250000,79.674531,0,1.26981,1
79,XOM,2018,1,0.442623,0.508197,0.196721,79.935574,0,1.12194,1
80,XOM,2017,4,0.539683,0.555556,0.317460,82.707381,0,1.03662,1
81,XOM,2017,3,0.507937,0.539683,0.253968,79.404444,1,0.86059,1
82,XOM,2017,2,0.444444,0.507937,0.190476,81.818571,0,0.83629,1
83,XOM,2017,1,0.403226,0.500000,0.193548,83.543065,1,0.84900,1
144,WMT,2019,4,0.484375,0.468750,0.203125,119.133906,1,1.09000,1
145,WMT,2019,3,0.453125,0.453125,0.203125,113.228594,1,1.22000,1
146,WMT,2019,2,0.619048,0.412698,0.238095,103.388730,1,1.02000,1
147,WMT,2019,1,0.524590,0.409836,0.245902,97.270656,1,1.33000,1
148,WMT,2018,4,0.555556,0.444444,0.238095,96.181905,1,1.01226,1
149,WMT,2018,3,0.444444,0.412698,0.238095,91.760159,1,1.21742,1
...,...,...,...,...,...,...,...,...,...,...
3390,ABT,2018,2,0.578125,0.531250,0.281250,60.625156,1,0.70972,1
3391,ABT,2018,1,0.524590,0.508197,0.229508,60.254426,1,0.58011,1
3392,ABT,2017,4,0.571429,0.460317,0.269841,55.418254,1,0.73217,1
3393,ABT,2017,3,0.539683,0.523810,0.222222,50.175397,1,0.65256,1
3394,ABT,2017,2,0.523810,0.428571,0.238095,45.265556,1,0.60500,1
3395,ABT,2017,1,0.596774,0.419355,0.290323,43.232903,1,0.43000,1
3456,AAPL,2019,4,0.656250,0.468750,0.296875,257.328750,1,4.55000,1
3457,AAPL,2019,3,0.500000,0.437500,0.218750,209.120703,1,2.84000,1
3458,AAPL,2019,2,0.539683,0.555556,0.206349,194.892698,1,2.10000,1
3459,AAPL,2019,1,0.540984,0.508197,0.278689,169.663770,1,2.36000,1
3460,AAPL,2018,4,0.460317,0.523810,0.222222,193.912063,1,4.16694,1
3461,AAPL,2018,3,0.571429,0.507937,0.269841,208.300000,1,2.78306,1
3462,AAPL,2018,2,0.546875,0.484375,0.203125,181.396562,1,2.18136,1
3463,AAPL,2018,1,0.442623,0.491803,0.213115,172.191311,1,2.67285,1
3464,AAPL,2017,4,0.523810,0.396825,0.206349,167.148254,1,3.85700,1
3465,AAPL,2017,3,0.523810,0.460317,0.253968,155.169048,1,1.86736,1
3466,AAPL,2017,2,0.412698,0.428571,0.174603,147.875397,1,1.57153,1
3467,AAPL,2017,1,0.645161,0.500000,0.370968,131.712500,1,2.01987,1
3528,A,2019,4,0.484375,0.468750,0.250000,78.725156,1,0.85000,1
3529,A,2019,3,0.453125,0.453125,0.156250,72.140000,1,0.72000,1
3530,A,2019,2,0.555556,0.507937,0.253968,74.087143,1,0.71000,1
3531,A,2019,1,0.639344,0.491803,0.278689,75.910164,1,0.73000,1
3532,A,2018,4,0.476190,0.507937,0.253968,67.278889,1,0.73592,1
3533,A,2018,3,0.587302,0.444444,0.269841,66.176349,1,0.62731,1
3534,A,2018,2,0.578125,0.437500,0.265625,65.249531,1,0.64239,1
3535,A,2018,1,0.442623,0.475410,0.180328,70.096066,1,0.58000,1
3536,A,2017,4,0.555556,0.476190,0.285714,67.493016,1,0.62433,1
3537,A,2017,3,0.492063,0.476190,0.158730,62.290476,1,0.52167,1
3538,A,2017,2,0.476190,0.428571,0.190476,56.958730,1,0.48357,1
3539,A,2017,1,0.580645,0.467742,0.290323,50.475645,1,0.49000,1

In [23]:
df_check = dd.loc[dd["Prediction"] == 0]
df_check

Empty DataFrame
Columns: [Prediction, Actual]
Index: []

# Hyperparameter Tuning

Use `GridSearchCV` to tune the model's parameters

In [24]:
# Create the GridSearchCV model
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.5, 1, 2], 'solver' : ['newton-cg', 'lbfgs', 'sag', 'saga']}

grid = GridSearchCV(classifier, param_grid, verbose = 3)

In [25]:
# Train the model with GridSearch
grid.fit(X_train_scaled, y_train)

C:\Users\ashka\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s

Fitting 3 folds for each of 12 candidates, totalling 36 fits
[CV] C=0.5, solver=newton-cg .........................................
[CV] ............. C=0.5, solver=newton-cg, score=0.800, total=   0.0s
[CV] C=0.5, solver=newton-cg .........................................
[CV] ............. C=0.5, solver=newton-cg, score=0.800, total=   0.0s
[CV] C=0.5, solver=newton-cg .........................................
[CV] ............. C=0.5, solver=newton-cg, score=0.801, total=   0.0s
[CV] C=0.5, solver=lbfgs .............................................
[CV] ................. C=0.5, solver=lbfgs, score=0.800, total=   0.0s
[CV] C=0.5, solver=lbfgs .............................................
[CV] ................. C=0.5, solver=lbfgs, score=0.800, total=   0.0s
[CV] C=0.5, solver=lbfgs .............................................
[CV] ................. C=0.5, solver=lbfgs, score=0.801, total=   0.0s
[CV] C=0.5, solver=sag ...............................................
[CV] ................... C=0.5, solver=sag, score=0.800, total=   0.0s
[CV] C=0.5, solver=sag ...............................................
[CV] ................... C=0.5, solver=sag, score=0.800, total=   0.0s
[CV] C=0.5, solver=sag ...............................................
[CV] ................... C=0.5, solver=sag, score=0.801, total=   0.0s
[CV] C=0.5, solver=saga ..............................................
[CV] .................. C=0.5, solver=saga, score=0.800, total=   0.0s
[CV] C=0.5, solver=saga ..............................................
[CV] .................. C=0.5, solver=saga, score=0.800, total=   0.0s
[CV] C=0.5, solver=saga ..............................................
[CV] .................. C=0.5, solver=saga, score=0.801, total=   0.0s
[CV] C=1, solver=newton-cg ...........................................
[CV] ............... C=1, solver=newton-cg, score=0.800, total=   0.0s
[CV] C=1, solver=newton-cg ...........................................
[CV] ............... C=1, solver=newton-cg, score=0.800, total=   0.0s
[CV] C=1, solver=newton-cg ...........................................
[CV] ............... C=1, solver=newton-cg, score=0.801, total=   0.0s
[CV] C=1, solver=lbfgs ...............................................
[CV] ................... C=1, solver=lbfgs, score=0.800, total=   0.0s
[CV] C=1, solver=lbfgs ...............................................
[CV] ................... C=1, solver=lbfgs, score=0.800, total=   0.0s
[CV] C=1, solver=lbfgs ...............................................
[CV] ................... C=1, solver=lbfgs, score=0.801, total=   0.0s
[CV] C=1, solver=sag .................................................
[CV] ..................... C=1, solver=sag, score=0.800, total=   0.0s
[CV] C=1, solver=sag .................................................
[CV] ..................... C=1, solver=sag, score=0.800, total=   0.0s
[CV] C=1, solver=sag .................................................
[CV] ..................... C=1, solver=sag, score=0.801, total=   0.0s
[CV] C=1, solver=saga ................................................
[CV] .................... C=1, solver=saga, score=0.800, total=   0.0s
[CV] C=1, solver=saga ................................................
[CV] .................... C=1, solver=saga, score=0.800, total=   0.0s
[CV] C=1, solver=saga ................................................
[CV] .................... C=1, solver=saga, score=0.801, total=   0.0s
[CV] C=2, solver=newton-cg ...........................................
[CV] ............... C=2, solver=newton-cg, score=0.800, total=   0.0s
[CV] C=2, solver=newton-cg ...........................................
[CV] ............... C=2, solver=newton-cg, score=0.800, total=   0.0s
[CV] C=2, solver=newton-cg ...........................................
[CV] ............... C=2, solver=newton-cg, score=0.801, total=   0.0s
[CV] C=2, solver=lbfgs ...............................................
[CV] ................... C=2, solver=lbfgs, score=0.800, total=   0.0s
[CV] C=2, solver=lbfgs ...............................................
[CV] ................... C=2, solver=lbfgs, score=0.800, total=   0.0s
[CV] C=2, solver=lbfgs ...............................................
[CV] ................... C=2, solver=lbfgs, score=0.801, total=   0.0s
[CV] C=2, solver=sag .................................................
[CV] ..................... C=2, solver=sag, score=0.800, total=   0.0s
[CV] C=2, solver=sag .................................................
[CV] ..................... C=2, solver=sag, score=0.800, total=   0.0s
[CV] C=2, solver=sag .................................................
[CV] ..................... C=2, solver=sag, score=0.801, total=   0.0s
[CV] C=2, solver=saga ................................................
[CV] .................... C=2, solver=saga, score=0.800, total=   0.0s
[CV] C=2, solver=saga ................................................
[CV] .................... C=2, solver=saga, score=0.800, total=   0.0s
[CV] C=2, solver=saga ................................................
[CV] .................... C=2, solver=saga, score=0.801, total=   0.0s

[Parallel(n_jobs=1)]: Done  36 out of  36 | elapsed:    0.2s finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.5, 1, 2],
                         'solver': ['newton-cg', 'lbfgs', 'sag', 'saga']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [26]:
print(grid.best_params_)
print(grid.best_score_)

{'C': 0.5, 'solver': 'newton-cg'}
0.8003333333333333

In [27]:
predictions = grid.predict(X_test_scaled)

In [28]:
target_names = ["Not Beat", "Beat"]

In [29]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=target_names))

              precision    recall  f1-score   support

    Not Beat       0.00      0.00      0.00        78
        Beat       0.87      1.00      0.93       522

    accuracy                           0.87       600
   macro avg       0.43      0.50      0.47       600
weighted avg       0.76      0.87      0.81       600

C:\Users\ashka\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [30]:
print(f"Training Data Score: {grid.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {grid.score(X_test_scaled, y_test)}")

Training Data Score: 0.8003333333333333
Testing Data Score: 0.87

In [31]:
gg = pd.DataFrame({"Prediction": predictions, "Actual":y_test})
gg

      Prediction  Actual
0              1       0
1              1       0
2              1       1
3              1       1
4              1       0
5              1       1
6              1       1
7              1       1
8              1       1
9              1       1
10             1       1
11             1       1
72             1       0
73             1       1
74             1       0
75             1       0
76             1       1
77             1       1
78             1       0
79             1       0
80             1       0
81             1       1
82             1       0
83             1       1
144            1       1
145            1       1
146            1       1
147            1       1
148            1       1
149            1       1
...          ...     ...
3390           1       1
3391           1       1
3392           1       1
3393           1       1
3394           1       1
3395           1       1
3456           1       1
3457           1       1
3458           1       1
3459           1       1
3460           1       1
3461           1       1
3462           1       1
3463           1       1
3464           1       1
3465           1       1
3466           1       1
3467           1       1
3528           1       1
3529           1       1
3530           1       1
3531           1       1
3532           1       1
3533           1       1
3534           1       1
3535           1       1
3536           1       1
3537           1       1
3538           1       1
3539           1       1

[600 rows x 2 columns]

In [32]:
s = gg["Prediction"].count()
wrong = 0
for i in range(0,s):
    a=gg["Prediction"].iloc[i]
    b=gg["Actual"].iloc[i]
    if a != b:
        wrong = wrong + 1
        
(s - wrong) / s

0.87